In [30]:
import pandas as pd
import numpy as np

df = pd.read_csv('D:/4th/bigdatasys/bsd-project/bigdatasys-proj/Random_Delivery_Data_with_Neighborhoods.csv')

df.head()

,Date,ORDERDAYWEEK,AREA,Cuisine,Population,Age_Range,Dilv_Dist,NoDel,Weather,FType
0,2020-09-22,토요일,경상남도 창원시 성산구 상남동,일식,482958,20대,550~1850,11,CLOUD,2인 가구
1,2020-10-25,목요일,대전광역시 유성구 봉명동,디저트,648096,50대,50~1950,8,SUN,2인 가구
2,2020-11-24,화요일,전라북도 전주시 완산구 서신동,일식,389697,80대,350~1900,29,SUN,다세대 가구
3,2020-07-18,목요일,서울특별시 강남구 역삼동,중식,313304,70대,100~1300,22,CLOUD,다세대 가구
4,2020-09-04,수요일,대구광역시 중구 동인동,중식,868687,50대,700~1050,6,WIND,다세대 가구

In [31]:
df['DO'] = np.nan
df['SI'] = np.nan
df['GU'] = np.nan
df['DONG'] = np.nan

In [32]:
df

,Date,ORDERDAYWEEK,AREA,Cuisine,Population,Age_Range,Dilv_Dist,NoDel,Weather,FType,DO,SI,GU,DONG
0,2020-09-22,토요일,경상남도 창원시 성산구 상남동,일식,482958,20대,550~1850,11,CLOUD,2인 가구,NaN,NaN,NaN,NaN
1,2020-10-25,목요일,대전광역시 유성구 봉명동,디저트,648096,50대,50~1950,8,SUN,2인 가구,NaN,NaN,NaN,NaN
2,2020-11-24,화요일,전라북도 전주시 완산구 서신동,일식,389697,80대,350~1900,29,SUN,다세대 가구,NaN,NaN,NaN,NaN
3,2020-07-18,목요일,서울특별시 강남구 역삼동,중식,313304,70대,100~1300,22,CLOUD,다세대 가구,NaN,NaN,NaN,NaN
4,2020-09-04,수요일,대구광역시 중구 동인동,중식,868687,50대,700~1050,6,WIND,다세대 가구,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,2020-12-10,화요일,서울특별시 종로구 청운효자동,디저트,98957,40대,850~1800,30,SNOW,독신 가구,NaN,NaN,NaN,NaN
69996,2020-07-10,토요일,세종특별자치시 고운동,기타,282205,30대,150~1900,3,SUN,2인 가구,NaN,NaN,NaN,NaN
69997,2020-12-11,월요일,서울특별시 강남구 역삼동,중식,690409,40대,750~1250,16,CLOUD,2인 가구,NaN,NaN,NaN,NaN
69998,2020-08-26,일요일,대구광역시 중구 동인동,일식,885416,50대,50~1950,16,CLOUD,2인 가구,NaN,NaN,NaN,NaN
69999,2020-11-08,목요일,대구광역시 중구 동인동,분식,762474,20대,450~1500,16,RAIN,2인 가구,NaN,NaN,NaN,NaN

In [33]:
def categorize_area(row):
    parts = row['AREA'].split()
    for part in parts:
        if part.endswith('도'):
            row['DO'] = part
        elif part.endswith('시'):
            row['SI'] = part
        elif part.endswith('구'):
            row['GU'] = part
        elif part.endswith('동'):
            row['DONG'] = part
    return row

In [34]:
df = df.apply(categorize_area, axis=1)

df

,Date,ORDERDAYWEEK,AREA,Cuisine,Population,Age_Range,Dilv_Dist,NoDel,Weather,FType,DO,SI,GU,DONG
0,2020-09-22,토요일,경상남도 창원시 성산구 상남동,일식,482958,20대,550~1850,11,CLOUD,2인 가구,경상남도,창원시,성산구,상남동
1,2020-10-25,목요일,대전광역시 유성구 봉명동,디저트,648096,50대,50~1950,8,SUN,2인 가구,NaN,대전광역시,유성구,봉명동
2,2020-11-24,화요일,전라북도 전주시 완산구 서신동,일식,389697,80대,350~1900,29,SUN,다세대 가구,전라북도,전주시,완산구,서신동
3,2020-07-18,목요일,서울특별시 강남구 역삼동,중식,313304,70대,100~1300,22,CLOUD,다세대 가구,NaN,서울특별시,강남구,역삼동
4,2020-09-04,수요일,대구광역시 중구 동인동,중식,868687,50대,700~1050,6,WIND,다세대 가구,NaN,대구광역시,중구,동인동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,2020-12-10,화요일,서울특별시 종로구 청운효자동,디저트,98957,40대,850~1800,30,SNOW,독신 가구,NaN,서울특별시,종로구,청운효자동
69996,2020-07-10,토요일,세종특별자치시 고운동,기타,282205,30대,150~1900,3,SUN,2인 가구,NaN,세종특별자치시,NaN,고운동
69997,2020-12-11,월요일,서울특별시 강남구 역삼동,중식,690409,40대,750~1250,16,CLOUD,2인 가구,NaN,서울특별시,강남구,역삼동
69998,2020-08-26,일요일,대구광역시 중구 동인동,일식,885416,50대,50~1950,16,CLOUD,2인 가구,NaN,대구광역시,중구,동인동
69999,2020-11-08,목요일,대구광역시 중구 동인동,분식,762474,20대,450~1500,16,RAIN,2인 가구,NaN,대구광역시,중구,동인동

In [35]:
df.drop('AREA', axis=1, inplace=True)

In [36]:
df.to_csv('delivery.csv', index=False)

In [24]:
# # 첫번째분할 후 1) 시인거 분류 2)도인거분류
# df['First_Word'] = df['AREA'].str.split(' ').str[0]
# df_filtered = df[df['First_Word'].str.endswith('시')]

# print(df_filtered)

             Date ORDERDAYWEEK             AREA Cuisine  Population Age_Range  \
1      2020-10-25          목요일    대전광역시 유성구 봉명동     디저트      648096       50대
3      2020-07-18          목요일    서울특별시 강남구 역삼동      중식      313304       70대
4      2020-09-04          수요일     대구광역시 중구 동인동      중식      868687       50대
9      2020-08-08          화요일     광주광역시 서구 화정동      분식      992209       80대
11     2020-11-24          금요일  서울특별시 종로구 청운효자동     디저트        8893       50대
...           ...          ...              ...     ...         ...       ...
69995  2020-12-10          화요일  서울특별시 종로구 청운효자동     디저트       98957       40대
69996  2020-07-10          토요일      세종특별자치시 고운동      기타      282205       30대
69997  2020-12-11          월요일    서울특별시 강남구 역삼동      중식      690409       40대
69998  2020-08-26          일요일     대구광역시 중구 동인동      일식      885416       50대
69999  2020-11-08          목요일     대구광역시 중구 동인동      분식      762474       20대

      Dilv_Dist  NoDel Weather   FType First_Word
1       50~1950      8     SUN   2인 가구      대전광역시
3      100~1300     22   CLOUD  다세대 가구      서울특별시
4      700~1050      6    WIND  다세대 가구      대구광역시
9      350~1750      3    SNOW   독신 가구      광주광역시
11     750~1950     11    WIND   독신 가구      서울특별시
...         ...    ...     ...     ...        ...
69995  850~1800     30    SNOW   독신 가구      서울특별시
69996  150~1900      3     SUN   2인 가구    세종특별자치시
69997  750~1250     16   CLOUD   2인 가구      서울특별시
69998   50~1950     16   CLOUD   2인 가구      대구광역시
69999  450~1500     16    RAIN   2인 가구      대구광역시

[34903 rows x 11 columns]

In [25]:
unique_values = df_filtered['AREA'].unique()
unique_values

array(['대전광역시 유성구 봉명동', '서울특별시 강남구 역삼동', '대구광역시 중구 동인동', '광주광역시 서구 화정동',
       '서울특별시 종로구 청운효자동', '인천광역시 남동구 구월동', '세종특별자치시 고운동', '부산광역시 해운대구 중동',
       '울산광역시 남구 신정동'], dtype=object)

In [26]:
df_filtered['second_Word'] = df_filtered['AREA'].str.split(' ').str[1]
df_gu_filtered = df_filtered[df_filtered['second_Word'].str.endswith('구')]

C:\Users\skfo9\AppData\Local\Temp\ipykernel_3160\3280397507.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['second_Word'] = df_filtered['AREA'].str.split(' ').str[1]

In [21]:
# 'AREA' 컬럼을 띄어쓰기 기준으로 분할하여 새로운 컬럼으로 나누기
# df_filtered[['Part1', 'Part2', 'Part3']] = df_filtered['AREA'].str.split(' ', expand=True)
# df_filtered['Part1'], df_filtered['Part2'],df_filtered['Part3'], df_filtered['Part4'] = df_filtered['AREA'].str.split(' ', expand=True)


# unique_values = df_filtered['AREA'].unique()

# unique_values

In [22]:
# df_filtered['도'] = df_filtered['AREA'].str.split(' ').str[0]

# df_filtered

C:\Users\skfo9\AppData\Local\Temp\ipykernel_3160\2137457817.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['도'] = df_filtered['AREA'].str.split(' ').str[0]

,Date,ORDERDAYWEEK,AREA,Cuisine,Population,Age_Range,Dilv_Dist,NoDel,Weather,FType,First_Word,도
0,2020-09-22,토요일,경상남도 창원시 성산구 상남동,일식,482958,20대,550~1850,11,CLOUD,2인 가구,경상남도,경상남도
2,2020-11-24,화요일,전라북도 전주시 완산구 서신동,일식,389697,80대,350~1900,29,SUN,다세대 가구,전라북도,전라북도
5,2020-11-15,화요일,전라남도 목포시 용당동,기타,446854,60대,50~1450,26,WIND,다세대 가구,전라남도,전라남도
6,2020-07-31,금요일,경기도 수원시 팔달구 인계동,패스트푸드,9533,20대,1000~1850,29,CLOUD,다세대 가구,경기도,경기도
7,2020-09-11,일요일,충청북도 청주시 상당구 탑동,양식,50531,10대,800~1150,11,WIND,2인 가구,충청북도,충청북도
...,...,...,...,...,...,...,...,...,...,...,...,...
69989,2020-09-08,일요일,전라남도 목포시 용당동,일식,31075,50대,350~1800,12,CLOUD,2인 가구,전라남도,전라남도
69990,2020-10-29,수요일,경기도 수원시 팔달구 인계동,분식,831277,80대,150~1250,21,SUN,독신 가구,경기도,경기도
69991,2020-12-30,월요일,전라북도 전주시 완산구 서신동,분식,379794,80대,50~1250,11,SNOW,독신 가구,전라북도,전라북도
69993,2020-12-27,일요일,충청남도 천안시 서북구 쌍용동,양식,968972,60대,450~1200,11,RAIN,다세대 가구,충청남도,충청남도
69994,2020-11-01,화요일,경상남도 창원시 성산구 상남동,패스트푸드,748973,80대,950~1600,3,SUN,다세대 가구,경상남도,경상남도